name = "html-go"
compatibility_date = "2023-01-01"

# 配置 Cloudflare Pages
[site]
bucket = "./dist"
pages_build_output_dir = "dist"

# 配置 D1 数据库
[[d1_databases]]
binding = "DB"
database_name = "html-go-db"
database_id = "2a5bd74e-ae8e-493e-9d26-9fd0a611ee20"
